//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1092.0 using the following command:
// xscgen --netCore --nullable --namespace=BioC --collectionType=System.Collections.Generic.List`1 --complexTypesForCollections=false --compactTypeNames --nullableReferenceAttributes --separateFiles --unionCommonType -o .. BioC.xsd
namespace BioC
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1092.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("passage", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("passage", Namespace="")]
    public partial class Passage
    {
        
        [XmlIgnoreAttribute()]
        private List<Infon> _infon;
        
        [XmlElementAttribute("infon")]
        public List<Infon> Infon
        {
            get
            {
                return _infon;
            }
            private set
            {
                _infon = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Infon collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InfonSpecified
        {
            get
            {
                return (this.Infon.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Passage" /> class.</para>
        /// </summary>
        public Passage()
        {
            this._infon = new List<Infon>();
            this._annotation = new List<Annotation>();
            this._sentence = new List<Sentence>();
            this._relation = new List<Relation>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("offset")]
        public string Offset { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlElementAttribute("text")]
        public string Text { get; set; }
        
        [XmlIgnoreAttribute()]
        private List<Annotation> _annotation;
        
        [XmlElementAttribute("annotation")]
        public List<Annotation> Annotation
        {
            get
            {
                return _annotation;
            }
            private set
            {
                _annotation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Annotation collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool AnnotationSpecified
        {
            get
            {
                return (this.Annotation.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<Sentence> _sentence;
        
        [XmlElementAttribute("sentence")]
        public List<Sentence> Sentence
        {
            get
            {
                return _sentence;
            }
            private set
            {
                _sentence = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Sentence collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SentenceSpecified
        {
            get
            {
                return (this.Sentence.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<Relation> _relation;
        
        [XmlElementAttribute("relation")]
        public List<Relation> Relation
        {
            get
            {
                return _relation;
            }
            private set
            {
                _relation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Relation collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RelationSpecified
        {
            get
            {
                return (this.Relation.Count != 0);
            }
        }
    }
}
