@Preon.WebApi_HostAddress = http://localhost:8544

###

GET {{Preon.WebApi_HostAddress}}/ping
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find?text=gh1
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find?text=test
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find?text=a87b3c5e-bb8b-46c8-931d-dd56d332934a
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find?text=1
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/?count=3
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find-exact?text=root
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find-closest-name?text=gh
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find-closest-name?text=image:Aethopyga temminckii
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find-by-namespaced-id
    ?idNamespace=ncbi-taxonomy
    &id=1118498
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/c126a52f-cc5d-43f4-9dff-70ebb62c3910
Accept: application/json



