@Preon.WebApi_HostAddress = http://localhost:8544

###

GET {{Preon.WebApi_HostAddress}}/ping
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/normalizer/query
    ?s=gh1
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/normalizer/query
    ?s=root
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/normalizer/wait
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/?count=3
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find-exact?text=root
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find-closest-name?text=gh
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find-closest-name?text=image:Aethopyga temminckii
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/find-by-namespaced-id
    ?idNamespace=ncbi-taxonomy
    &id=1118498
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/3b801914-3a5e-4225-a43b-f83a670a9fb1
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/254
Accept: application/json



