@Preon.WebApi_HostAddress = http://localhost:8544

###

GET {{Preon.WebApi_HostAddress}}/ping
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/normalizer/query
    ?s=gh1
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/normalizer/query
    ?s=root
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/normalizer/wait
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/?count=3
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/search?text=gh-1
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/dd4ea83a-4d98-4d85-85fd-e68b23692565
Accept: application/json

###

GET {{Preon.WebApi_HostAddress}}/taxonomy/254
Accept: application/json



