//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1092.0 using the following command:
// xscgen --netCore --nullable --namespace=BioCXml --collectionType=System.Collections.Generic.List`1 --complexTypesForCollections=false --compactTypeNames --nullableReferenceAttributes --separateFiles --unionCommonType -o .. BioC.xsd
namespace BioCXml
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1092.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("document", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("document", Namespace="")]
    public partial class Document
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("id")]
        public string Id { get; set; }
        
        [XmlIgnoreAttribute()]
        private List<Infon> _infon;
        
        [XmlElementAttribute("infon")]
        public List<Infon> Infon
        {
            get
            {
                return _infon;
            }
            private set
            {
                _infon = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Infon collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InfonSpecified
        {
            get
            {
                return (this.Infon.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Document" /> class.</para>
        /// </summary>
        public Document()
        {
            this._infon = new List<Infon>();
            this._passage = new List<Passage>();
            this._relation = new List<Relation>();
        }
        
        [XmlIgnoreAttribute()]
        private List<Passage> _passage;
        
        [RequiredAttribute()]
        [XmlElementAttribute("passage")]
        public List<Passage> Passage
        {
            get
            {
                return _passage;
            }
            private set
            {
                _passage = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<Relation> _relation;
        
        [XmlElementAttribute("relation")]
        public List<Relation> Relation
        {
            get
            {
                return _relation;
            }
            private set
            {
                _relation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Relation collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RelationSpecified
        {
            get
            {
                return (this.Relation.Count != 0);
            }
        }
    }
}
