//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1092.0 using the following command:
// xscgen --netCore --nullable --namespace=PreonUsage.BioC --collectionType=System.Collections.Generic.List`1 --complexTypesForCollections=false --compactTypeNames --nullableReferenceAttributes --separateFiles --unionCommonType --namespaceHierarchy PreonUsage/BioC.xsd
namespace PreonUsage.BioC
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1092.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("annotation", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("annotation", Namespace="")]
    public partial class Annotation : IAttlistAnnotation
    {
        
        [XmlIgnoreAttribute()]
        private List<Infon> _infon;
        
        [XmlElementAttribute("infon")]
        public List<Infon> Infon
        {
            get
            {
                return _infon;
            }
            private set
            {
                _infon = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Infon collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InfonSpecified
        {
            get
            {
                return (this.Infon.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Annotation" /> class.</para>
        /// </summary>
        public Annotation()
        {
            this._infon = new List<Infon>();
            this._location = new List<Location>();
        }
        
        [XmlIgnoreAttribute()]
        private List<Location> _location;
        
        [XmlElementAttribute("location")]
        public List<Location> Location
        {
            get
            {
                return _location;
            }
            private set
            {
                _location = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Location collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool LocationSpecified
        {
            get
            {
                return (this.Location.Count != 0);
            }
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("text")]
        public string Text { get; set; }
        
        [AllowNullAttribute()]
        [MaybeNullAttribute()]
        [XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
}
