//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1092.0 using the following command:
// xscgen --netCore --nullable --namespace=PreonUsage.BioC --collectionType=System.Collections.Generic.List`1 --complexTypesForCollections=false --compactTypeNames --nullableReferenceAttributes --separateFiles --unionCommonType --namespaceHierarchy PreonUsage/BioC.xsd
namespace PreonUsage.BioC
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1092.0")]
    public partial interface IAttlistInfon
    {
        
        string Key
        {
            get;
            set;
        }
    }
}
